name: 'W3X Builder'
description: 'Outputs a Warcraft III map with all assets stripped away.'
branding:
  icon: activity
  color: orange

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v2
  - name: Checkout and init submodules
    run: | 
      git clone https://github.com/TheLazzoro/war3-map-build-action
      git submodule update --init --recursive
      cd war3-map-build-action
    shell: bash
    with:
      repository: 'TheLazzoro/war3-map-build-action'

  - name: Setup .NET
    uses: actions/checkout@v2
    with:
      dotnet-version: 8.x
      repository: 'TheLazzoro/war3-map-build-action'

  - name: Run
    run: |
      ls
      dotnet restore
      dotnet build --no-restore
      dotnet publish ./W3X-Builder/W3X-Builder.csproj -c Release -o out --no-self-contained
      dotnet run ./W3X-Builder.dll
    shell: bash
    with:
      repository: 'TheLazzoro/war3-map-build-action'

