name: 'W3X Builder'
description: 'Outputs a Warcraft III map with all assets stripped away.'
branding:
  icon: activity
  color: orange

runs:
  using: 'composite'

  steps:

  - name: Setup .NET
    uses: actions/checkout@v2
    with:
      dotnet-version: 8.x
      repository: 'TheLazzoro/war3-map-build-action'

  - name: Run
    run: |
      ls
      git submodule update --init --recursive
      dotnet restore
      dotnet run --project ./W3X-Builder/W3X-Builder.csproj
      echo WORKING DIR
      pwd
      ls ./W3X-Builder/bin/Release/net8.0/
    shell: bash

# dotnet publish ./W3X-Builder/W3X-Builder.csproj -c Release -o out --no-self-contained
# ./W3X-Builder/bin/Release/net8.0/W3X-Builder.exe
  