name: 'W3X Builder'
description: 'Outputs a Warcraft III map with all assets stripped away.'
branding:
  icon: activity
  color: orange

runs:
  using: 'composite'

  steps:

  - name: Setup .NET
    uses: actions/checkout@v2
    with:
      dotnet-version: 8.x
      repository: 'TheLazzoro/war3-map-build-action'

  - name: Run
    shell: bash
    run: |
      ls
      echo REMOVING TEST FILES
      rm -R ./War3Net/tests

  - name: Archive Artifact
    uses: actions/upload-artifact@v4
    with:
      name: builder
      path: ./

  # Checks out repository that runs this action
  - name: Checkout repo
    uses: actions/checkout@v2

  - name: Download Artifact
    uses: actions/download-artifact@v4
    with:
      name: builder
      path: W3X-Builder

  - name: Run
    shell: bash
    run: |
      cd ./W3X-Builder/
      git submodule update --init --recursive
      dotnet restore
      dotnet build --no-restore
      dotnet run --project ./W3X-Builder/W3X-Builder.csproj
