name: 'W3X Builder'
description: 'Outputs a Warcraft III map with all assets stripped away.'
branding:
  icon: activity
  color: orange

runs:
  using: 'composite'
  steps:
  - name: Checkout submodules
    run: git submodule update --init --recursive
    shell: bash

  - name: Setup .NET
    uses: actions/checkout@v2
    with:
      dotnet-version: 8.x

  - name: Restore dependencies
    run: dotnet restore
    shell: bash

  - name: Build
    run: dotnet build --no-restore
    shell: bash

  - name: Run
    run: dotnet run /W3X-Builder.dll
    shell: bash
