name: 'W3X Builder'
description: 'Outputs a Warcraft III map with all assets stripped away.'
branding:
  icon: activity
  color: orange

runs:
  using: 'composite'

  steps:

  - name: Setup .NET
    uses: actions/checkout@v2
    with:
      dotnet-version: 8.x
      repository: 'TheLazzoro/war3-map-build-action'

  - name: Run
    run: |
      ls
      git submodule update --init --recursive
      dotnet restore
      dotnet build --no-restore
      dotnet publish ./W3X-Builder/W3X-Builder.csproj -c Release -o out --no-self-contained
      echo WORKING DIR
      pwd
      dotnet run ./bin/Release/net8.0/W3X-Builder.dll
    shell: bash
