name: 'W3X Builder'
description: 'Outputs a Warcraft III map with all assets stripped away.'
branding:
  icon: activity
  color: orange
outputs:
  summary-title:
    description:
      'Outputs a Warcraft III map with all assets stripped away.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - BUILDKIT_CONTEXT_KEEP_GIT_DIR=true
